# TCL File Generated by Component Editor 24.1
# Thu May 30 13:43:48 CDT 2024
# DO NOT MODIFY


# 
# custom_pwm_hw "custom_pwm" v1.0
#  2024.05.30.13:43:48
# 
# 

# 
# request TCL package from ACDS 24.1
# 
package require -exact qsys 24.1


# 
# module custom_pwm_hw
# 
set_module_property DESCRIPTION ""
set_module_property NAME custom_pwm_hw
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property BSP_CPU false
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME custom_pwm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property LOAD_ELABORATION_LIMIT 0
set_module_property PRE_COMP_MODULE_ENABLED false


# 
# file sets
# 
add_fileset custom_pwm QUARTUS_SYNTH "" ""
set_fileset_property custom_pwm TOP_LEVEL cust_pwm
set_fileset_property custom_pwm ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property custom_pwm ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cust_PwmCSR.vhd VHDL PATH cust_PwmCSR.vhd
add_fileset_file cust_PwmDataMux.vhd VHDL PATH cust_PwmDataMux.vhd
add_fileset_file cust_PwmRegisters.vhd VHDL PATH cust_PwmRegisters.vhd
add_fileset_file cust_pwm.vhd VHDL PATH cust_pwm.vhd TOP_LEVEL_FILE

add_fileset custom_pwm SIM_VERILOG "" ""
set_fileset_property custom_pwm TOP_LEVEL cust_pwm
set_fileset_property custom_pwm ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property custom_pwm ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cust_PwmCSR.vhd VHDL PATH cust_PwmCSR.vhd
add_fileset_file cust_PwmDataMux.vhd VHDL PATH cust_PwmDataMux.vhd
add_fileset_file cust_PwmRegisters.vhd VHDL PATH cust_PwmRegisters.vhd
add_fileset_file cust_pwm.vhd VHDL PATH cust_pwm.vhd TOP_LEVEL_FILE

add_fileset custom_pwm SIM_VHDL "" ""
set_fileset_property custom_pwm TOP_LEVEL cust_pwm
set_fileset_property custom_pwm ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property custom_pwm ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cust_PwmCSR.vhd VHDL PATH cust_PwmCSR.vhd
add_fileset_file cust_PwmDataMux.vhd VHDL PATH cust_PwmDataMux.vhd
add_fileset_file cust_PwmRegisters.vhd VHDL PATH cust_PwmRegisters.vhd
add_fileset_file cust_pwm.vhd VHDL PATH cust_pwm.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter NUM_CHANNELS INTEGER 12 ""
set_parameter_property NUM_CHANNELS DEFAULT_VALUE 12
set_parameter_property NUM_CHANNELS DISPLAY_NAME NUM_CHANNELS
set_parameter_property NUM_CHANNELS UNITS None
set_parameter_property NUM_CHANNELS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property NUM_CHANNELS DESCRIPTION ""
set_parameter_property NUM_CHANNELS AFFECTS_GENERATION false
set_parameter_property NUM_CHANNELS HDL_PARAMETER true
set_parameter_property NUM_CHANNELS EXPORT true
add_parameter CHANNEL_WIDTH INTEGER 24 ""
set_parameter_property CHANNEL_WIDTH DEFAULT_VALUE 24
set_parameter_property CHANNEL_WIDTH DISPLAY_NAME CHANNEL_WIDTH
set_parameter_property CHANNEL_WIDTH UNITS None
set_parameter_property CHANNEL_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CHANNEL_WIDTH DESCRIPTION ""
set_parameter_property CHANNEL_WIDTH AFFECTS_GENERATION false
set_parameter_property CHANNEL_WIDTH HDL_PARAMETER true
set_parameter_property CHANNEL_WIDTH EXPORT true
add_parameter ADDR_WIDTH INTEGER 4
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 4
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH AFFECTS_GENERATION false
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
set_parameter_property ADDR_WIDTH EXPORT true


# 
# display items
# 


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset
set_interface_property interrupt_sender bridgedReceiverOffset 0
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""
set_interface_property interrupt_sender IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property interrupt_sender SV_INTERFACE_TYPE ""
set_interface_property interrupt_sender SV_INTERFACE_MODPORT_TYPE ""

add_interface_port interrupt_sender interrupt irq Output 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""
set_interface_property clock IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property clock SV_INTERFACE_TYPE ""
set_interface_property clock SV_INTERFACE_MODPORT_TYPE ""

add_interface_port clock SysClk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""
set_interface_property reset IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property reset SV_INTERFACE_TYPE ""
set_interface_property reset SV_INTERFACE_MODPORT_TYPE ""

add_interface_port reset SysReset reset Input 1


# 
# connection point conduit
# 
add_interface conduit conduit end
set_interface_property conduit associatedClock clock
set_interface_property conduit associatedReset reset
set_interface_property conduit ENABLED true
set_interface_property conduit EXPORT_OF ""
set_interface_property conduit PORT_NAME_MAP ""
set_interface_property conduit CMSIS_SVD_VARIABLES ""
set_interface_property conduit SVD_ADDRESS_GROUP ""
set_interface_property conduit IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property conduit SV_INTERFACE_TYPE ""
set_interface_property conduit SV_INTERFACE_MODPORT_TYPE ""

add_interface_port conduit PwmOut name Output "((num_channels - 1)) - (0) + 1"


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressGroup 0
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave bridgedAddressOffset ""
set_interface_property avalon_slave bridgesToMaster ""
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave minimumResponseLatency 1
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave transparentBridge false
set_interface_property avalon_slave waitrequestAllowance 0
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave dfhFeatureGuid 0
set_interface_property avalon_slave dfhGroupId 0
set_interface_property avalon_slave dfhParameterId ""
set_interface_property avalon_slave dfhParameterName ""
set_interface_property avalon_slave dfhParameterVersion ""
set_interface_property avalon_slave dfhParameterData ""
set_interface_property avalon_slave dfhParameterDataLength ""
set_interface_property avalon_slave dfhFeatureMajorVersion 0
set_interface_property avalon_slave dfhFeatureMinorVersion 0
set_interface_property avalon_slave dfhFeatureId 35
set_interface_property avalon_slave dfhFeatureType 3
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""
set_interface_property avalon_slave IPXACT_REGISTER_MAP_VARIABLES ""
set_interface_property avalon_slave SV_INTERFACE_TYPE ""
set_interface_property avalon_slave SV_INTERFACE_MODPORT_TYPE ""

add_interface_port avalon_slave Address address Input "((addr_width - 1)) - (0) + 1"
add_interface_port avalon_slave WriteEn write Input 1
add_interface_port avalon_slave ReadEn read Input 1
add_interface_port avalon_slave ChipSelect chipselect Input 1
add_interface_port avalon_slave WriteData writedata Input 32
add_interface_port avalon_slave ReadData readdata Output 32
add_interface_port avalon_slave WaitRequest waitrequest Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

